import React from "react";
import Head from "next/head";
import HeaderNav from "@/components/HeaderNav";

const add = () => {
  return (
    <>
      <Head>
        <title>New Quiz</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderNav />
      <main className="w-1/2 mx-auto py-10">
        <h3 className="text-xl text-center">Create a New Quiz</h3>
        <input
          type="text"
          className="p-2 border border-gray-400 rounded-sm w-full my-2"
          placeholder="Enter Quiz Title"
        />
        <textarea
          className="p-2 border border-gray-400 rounded-sm w-full my-2"
          cols="30"
          placeholder="Enter Quiz Description"
        ></textarea>
        <input
          type="number"
          className="p-2 border border-gray-400 rounded-sm w-full my-2"
          placeholder="Enter Grading Points"
        />
        <input
          type="number"
          className="p-2 border border-gray-400 rounded-sm w-full my-2"
          placeholder="Enter Quiz Time in Minutes"
        />
      </main>
    </>
  );
};

export default add;
