import { useEffect, useState } from "react";
import Head from "next/head";
import { collection, getDocs } from "firebase/firestore";
import { db } from "../firebase";
import HeaderNav from "@/components/HeaderNav";

export default function Home() {
  const [quizes, setQuizes] = useState([]);
  const getData = async () => {
    const querySnapshot = await getDocs(collection(db, "quizes"));
    querySnapshot.forEach((doc) => {
      // console.log(`${doc.id} => ${doc.data()}`);
      setQuizes([...quizes, doc.data()]);
    });
  };
  useEffect(() => {
    getData();
  }, []);

  return (
    <>
      <Head>
        <title>My Quiz App</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderNav />
      <main className="px-32 py-10">
        <div className="flex flex-wrap justify-between">
          {quizes.map((quiz, index) => (
            <div key={index} className="lg:w-[32%] rounded-xl shadow my-4">
              <div className="w-full rounded-t-xl p-20 bg-purple-500 text-center">
                <div className="text-4xl my-auto capitalize">
                  {quiz.name[0]}
                </div>
              </div>
              <div className="p-3 flex justify-between">
                <div>
                  <div className="font-bold text-xl capitalize">
                    {quiz.name}
                  </div>
                  <p className="text-sm capitalize">{quiz.description}</p>
                  <p className="capitalize text-sm">
                    Created by: {quiz.author}
                  </p>
                </div>
                <button className="bg-gray-300 hover:bg-gray-200 h-8 my-auto px-2 rounded-md text-sm">
                  Take Quiz
                </button>
                {/* <div className="my-auto">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="20"
                    height="20"
                    fill="currentColor"
                    className="bi bi-three-dots-vertical"
                    viewBox="0 0 16 16"
                  >
                    <path d="M9.5 13a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z" />
                  </svg>
                </div> */}
              </div>
            </div>
          ))}
        </div>
      </main>
    </>
  );
}
